export { default as Nav } from "./Nav"
export { default as Sidebar } from "./Sidebar"
export { default as HeroSection } from "./HeroSection"
export { default as Offer } from "./Offer"
export { default as Softwares } from "./Softwares"
export { default as Platform } from "./Platform"